users:
  - default
  - name: jasondoze
    sudo: ALL=(ALL) NOPASSWD:ALL
    shell: /bin/bash
    ssh_authorized_keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIAyBdhhksKQNAqt/I0aamawUkGnDqbpyDkLyk6kYjd1I jasondoze@jd.attlocal.net
