users:
  - default
  - name: vmuser
    sudo: ALL=(ALL) NOPASSWD:ALL
    ssh_authorized_keys:
    - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDGnfoG8LLpfWES0el5xcoBq+mHqRx2eIZ9jxB9HwU++5WJjOVaRXF1PBl0ontxOtLsK0yJRnTwegs1Wns1iimcjfuTQuBj2d5ZWxqC1FLIWSGdOy2P+4V+hfpPz92uvCU0/EYFwhjLdMivPHDLhnt0m8OS58mYFctf+Oe+gHXrQR/eiedjr5a6snjtbdUV1s7I3r63m4qwXD8gE8Belw8seg9HZp9JskBLJf7pOE34+GZj460iPYUXOWZGG9dymutnXyLmh5EGqpv9cYN0bjCMM+8Lk7LM7yv/nNLt3wm7qFAzZRw1iIjUqJo2yNeZ+WcO73EdIqINWzDc8+Unjzf2XrfO+NoIeInWj257zoAaANwZQGaya0ATOB9iAfYZbzX35RhBhyL3AmHwUIXUBuDXmQFdtfX/T/Taq/YhZnagFgpfn3lVQUG5+9xzrGFTJLLk3UPKo/HagBRCqRkYOJ6W0Luj3on9LMTOM0icSQVdgTjTczS1ZVwk/sDiAOl3s5s= 
vmuser

